(in-package :utility)

(import 'serapeum:nor)
(import 'serapeum:nand)
(import 'serapeum:select)
(import 'serapeum:selector)
(import 'serapeum:eq*)
(import 'serapeum:eql*)
(import 'serapeum:equal*)
(import 'serapeum:equalp*)
